# -*- coding: utf-8 -*-
"""Fiverr Project 13.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DAyvBDwl5BeHmW_XAuZtXATR1VRegCp6
"""

import pandas as pd

df=pd.read_excel("Crowdfunding_data_1000_projects (2).xlsx")

"""1. Use Pandas functions head() and tail(), and create two data-frames with top 70 % records in the first data-frame, and remaining 30% records in the second data-frame (2 points)."""

df1=df.head(700)

df2=df.tail(300)

print("Train : ",len(df1))
print("Test  : ",len(df2))

"""2. Use Pandas functions sample() and drop(), and create two data-frames with random 70% of records in the first data-frame and remaining 30% of records in the second data-frame (4 points)."""

df3=df.sample(700)

df4=df.drop(index=df3.index)

print("Train : ",len(df3))
print("Test  : ",len(df4))

"""3. Use Scikit-learn package and create two data-frames with random 70% of records in the train data-frame and remaining 30% of records in test data-frame (4 points)."""

from sklearn.model_selection import train_test_split

df5,df6=train_test_split(df,test_size=0.3)

print("Train : ",len(df5))
print("Test  : ",len(df6))

