# -*- coding: utf-8 -*-
"""Pro_04.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Q3dDfhM9_lNStrVdLd44hnR6K19kc_B8
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

"""(i) Load the .csv file into the notebook."""

df=pd.read_csv("https://raw.githubusercontent.com/DataTensor/hdb/main/resale-flat-prices.csv")

df.sample(3)

"""(ii) Summarize the information that can be derived from the dataset, including key
features (columns), range of values, and missing / non-useful values. All the
information should be derived by necessary Python codes.
"""

df.columns

df.describe()

df.info()

df.isna().sum()# sum of missing values in each column

df.dtypes

df.shape

"""(iii) Explain TWO (2) potential insights that can be derived from the dataset."""

df.groupby("lease_commence_date").mean()["resale_price"].plot()

df.groupby("flat_model").mean()["resale_price"]

"""(i) Refer to Q1(a)(ii), remove all the data rows with missing data values."""

df.dropna(inplace=True)
df.shape

"""(ii) In Singapore, HDB flats have a 99 years’ leasehold. Compute the remaining
lease in years for each transacted flat on its transacted date.
"""

remaining_lease_in_years = 99-(2021-df["lease_commence_date"])

remaining_lease_in_years

df["remaining_lease_in_years"] = remaining_lease_in_years

"""(iii) List out the top ten of remaining lease in years (computed by Q1(b)(ii) having
the greatest number of transacted flats.
"""

df.groupby("remaining_lease_in_years").count().sort_values(by="street_name",ascending=False).head(10).index

df.to_csv("Cleaned.csv")

df.head(1)