# -*- coding: utf-8 -*-
"""Fiverr Project 14.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1klGReGngq-NqVSe_kO89Fd1zAbEiYXKt
"""

import pandas as pd

def foo(a):
  a.drop_duplicates(inplace=True)
  b=a.iloc[:,[-1,0]].copy()
  b.columns=["Employee","Boss"]
  return b

def foo2(table):
  g=pd.DataFrame(columns=["Employee","Boss"])
  table.insert(0,"Empty Column","")
  table.dropna(inplace=True)
  for a in range(0,table.shape[1]-1):
    df2=table.iloc[:,[a,a+1]].copy()
    f=foo(df2)
    g=pd.concat([g,f])
  table.drop(columns="Empty Column",inplace=True)
  return g

df=pd.read_excel("data2.xlsx")
df.head()

df1=df.iloc[:,[0,1,2,3,4,5]].copy()
desired=foo2(df1)
desired.index=[f for f in range(0,len(desired))]
desired

a=pd.DataFrame(desired.Boss.value_counts())
a.insert(0,"Employee",a.index)
a["Direct Report"]=a.Boss.values
a.drop(columns=["Boss"],inplace=True)

a.index=[f for f in range(0,len(a))]

a

desired1=pd.merge(desired,a,on="Employee",how="left").fillna(0)

desired1["Direct Report"]=desired1["Direct Report"].astype("int")

desired1

