# -*- coding: utf-8 -*-
"""Pandas DataFrame.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BTtngEHgoKQhuee0P64knPdjA50UR6vP
"""

import pandas as pd

data=pd.read_excel("/content/Crowdfunding_data_1000_projects (5).xlsx")

"""1. Create a pandas data-frame with columns: (1) Project_ID; (2) School_city; (3) Goal; (4) num_donors. (2 points)"""

df=data.loc[:,["Project_ID","school_city","Goal","num_donors"]]

"""2. Show mean values of Goal and num_donors for each school_city using groupby() function. (2 points)"""

df1=df.iloc[:,[1,2,3]]
df1.groupby(["school_city"]).mean()

"""3. Present descriptive statistics for the data-frame. using describe() function. (2 points)"""

df.describe()

"""4. Create another data-frame from Crowdfunding_data_1000_projects.xlsxPreview the document with columns: (1) Project_ID ; (2) school_state, and merge with data-frame from step (1). (2 points)"""

df2=data.loc[:,["Project_ID","school_state"]]

merged=pd.merge(df,df2)
merged

"""5. Using the merged data-frame from step (4), select rows where school_state is MO and num_donors>1. (2 points)"""

final=merged[(merged["school_state"]=="MO") & (merged["num_donors"]>1)]
final

