# -*- coding: utf-8 -*-
"""addfile.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dpwhixe45PSIJVJA3TFXA8KiMKWAXOxc
"""

import os
path="/content/gdrive/MyDrive/Checking Folder"
#path="/andreaaloia101-attachments"
list=os.listdir(path)
li=[]
for a in list:
  if os.path.isfile(os.path.join(path,a)):
    li.append(a)
try:
  li.remove("Recap.csv")
except ValueError:
  pass
files_list=li
dict={}
for a in li:
  b=a.split(".")
  if len(b)==2:
    dict[b[1]]=[]
for a in li:
  b=a.split(".")
  if len(b)==2:
    dict[b[1]].append(b[0])
ldf=[]
for aa in dict.keys():
  path1=path+"/"+aa+" files"
  try:
    os.makedirs(path1)
    ldf.append(path1)
  except:
    continue
import csv
for a in files_list:
  if os.path.exists(path+"/"+"Recap.csv")==False:
    with open(path+"/"+"Recap.csv","a") as f:
      ff=csv.writer(f,delimiter=",")
      ff.writerow(["Name","Type","Size"])
      ff.writerow([a.split(".")[0],a.split(".")[-1],os.stat(path+"/"+a).st_size])
  else:
    with open(path+"/"+"Recap.csv","a") as f:
      ff=csv.writer(f,delimiter=",")
      ff.writerow([a.split(".")[0],a.split(".")[-1],os.stat(path+"/"+a).st_size])
import shutil
for aa in dict.keys():
  for bb in dict[aa]:
    shutil.move(path+"/"+bb+"."+aa,path+"/"+aa+" files")

